import Head from 'next/head'
import HomeCards from '../Components/home/HomeCards'
import FreeShipping from '../Components/Layout/FreeShipping'
import Layout from '../Components/Layout/Layout'
import YourName from '../Components/home/YourName'
import Connect from '../Components/home/Connect'
import InstaFeed from '../Components/home/InstaFeed'
import Header from '../Components/home/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home - gtex uniforms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Layout>
          <FreeShipping />
          <Header />
          <HomeCards marginTop={'mt-[40px]'}/>
          <HomeCards reverse={'flex-row-reverse'} mt={'-mt-[6px]'} />
          <HomeCards mt={'-mt-[6px]'} pb={'pb-[40px]'} />
          <YourName />
          <InstaFeed />
          <Connect />
        </Layout>
      </>
    </div>
  )
}
